# Create Globus Endpoint

#- name: Configure endpoint name
# Get name from user
# http://docs.ansible.com/ansible/latest/user_guide/playbooks_prompts.html
#
# Edit config file
# http://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
#
#- name: Setup server
#  command: globus-connect-server-setup
#  use expect prompts
#  http://docs.ansible.com/ansible/latest/modules/expect_module.html
