# Install Globus Connect Server

#- name: Request Globus Connect Server RPM and download into local directory
#  get_url:
#    url: https://downloads.globus.org/toolkit/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
#    dest: "{{ playbook_dir }}"

- name: Add Globus key to local GPG keyring
  rpm_key:
    key: https://downloads.globus.org/toolkit/gt6/stable/repo/rpm/RPM-GPG-KEY-Globus

# This RPM is not getting installed properly
- name: Install Globus Connect RPM
  yum:
    name: https://downloads.globus.org/toolkit/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
    state: latest

- name: Request EPEL repository and download into local directory
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: "{{ playbook_dir }}"

- name: Install EPEL
  yum:
    name: epel-release-latest-7.noarch.rpm

- name: Install Prerequisite packages
  yum:
    name: yum-plugin-priorities
    state: latest

- name: Install Globus Connect Server
  yum:
    name: globus-connect-server
    state: latest

#?
