# Install Globus Connect Server

- name: Request latest version of software via HTTP
  command: curl -LOs https://downloads.globus.org/toolkit/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
  command: rpm --import https://downloads.globus.org/toolkit/gt6/stable/repo/rpm/RPM-GPG-KEY-Globus
  yum:
    - name: globus-connect-server-repo-latest.noarch.rpm
    - state: present

- name: Install EPEL repository and Prerequisite packages
  command: curl -LOs https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  command: yum install epel-release-latest-7.noarch.rpm
  command: yum install yum-plugin-priorities

- name: Install Globus Connect Server
  command: yum install globus-connect-server

